catalogMode: prefer
shellEmulator: true

packages:
  - docs
  - playground
  - packages/**
  - examples/**

catalogs:
  ast:
    magic-string-ast: ^1.0.3
    oxc-parser: ~0.101.0
  build:
    tsdown: ^0.17.4
    unbuild: ^3.6.1
    unplugin: ^2.3.11
    unplugin-utils: ^0.3.1
  cli:
    "@antfu/ni": ^28.0.0
    bumpp: ^10.3.2
    pncat: ^0.7.7
  lint:
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  script:
    esno: ^4.8.0
  test:
    vitest: ^4.0.15
  tsc:
    typescript: ~5.9.3
  types:
    "@types/node": ^22.19.3
  xiaohe:
    "@xiaohe01/eslint-config": ^4.1.0
    "@xiaohe01/tsconfig": ^3.1.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks