packages:
  - docs
  - playground
  - packages/**
  - examples/**
catalogs:
  ast:
    magic-string-ast: ^1.0.3
    oxc-parser: ~0.99.0
  build:
    tsdown: ^0.16.7
    unbuild: ^3.6.1
    unplugin: ^2.3.11
    unplugin-utils: ^0.3.1
  cli:
    "@antfu/ni": ^27.0.1
    bumpp: ^10.3.1
    pncat: ^0.7.6
  lint:
    eslint: ^9.39.1
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  script:
    esno: ^4.8.0
  test:
    vitest: ^4.0.14
  tsc:
    typescript: ~5.9.3
  types:
    "@types/node": ^22.19.1
  xiaohe:
    "@xiaohe01/eslint-config": ^4.0.0
    "@xiaohe01/tsconfig": ^3.0.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks